name: Test Kaizen Unit Test Runner Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-python-pip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create Python test environment
      run: |
        mkdir -p tests
        echo "def test_success(): assert True" > .kaizen/unit_test/tests/test_success.py
        echo "def test_failure(): assert False" > .kaizen/unit_test/tests/test_failure.py
        echo "pytest==7.3.1" > requirements.txt
    - name: Run Kaizen Unit Test Runner Action
      uses: ./
      continue-on-error: true
    - name: Verify output
      run: |
        if ! grep -q "1 passed, 1 failed" $GITHUB_STEP_SUMMARY; then
          echo "Expected output not found in step summary"
          exit 1
        fi

  test-python-poetry:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create Python Poetry test environment
      run: |
        mkdir -p tests
        echo "def test_poetry(): assert True" > .kaizen/unit_test/tests/test_poetry.py
        echo "[tool.poetry]
        name = \"test-project\"
        version = \"0.1.0\"
        description = \"\"
        authors = [\"Test Author <test@example.com>\"]

        [tool.poetry.dependencies]
        python = \"^3.9\"
        pytest = \"^7.3.1\"

        [build-system]
        requires = [\"poetry-core\"]
        build-backend = \"poetry.core.masonry.api\"" > pyproject.toml
    - name: Run Kaizen Unit Test Runner Action
      uses: ./

  test-javascript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create JavaScript test environment
      run: |
        echo '{
          "name": "test-project",
          "version": "1.0.0",
          "scripts": {
            "test": "jest"
          },
          "devDependencies": {
            "jest": "^29.5.0"
          }
        }' > package.json
        echo 'module.exports = { testEnvironment: "node" };' > .kaizen/unit_test/jest.config.js
        echo 'test("sample test", () => { expect(true).toBe(true); });' > .kaizen/unit_test/test.js
    - name: Run Kaizen Unit Test Runner Action
      uses: ./

  test-react:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create React test environment
      run: |
        echo '{
          "name": "test-react-app",
          "version": "0.1.0",
          "private": true,
          "dependencies": {
            "react": "^18.2.0",
            "react-dom": "^18.2.0",
            "react-scripts": "5.0.1"
          },
          "scripts": {
            "test": "react-scripts test --env=jsdom"
          }
        }' > package.json
        mkdir src
        echo 'test("dummy test", () => { expect(true).toBe(true); });' > .kaizen/unit_test/src/App.test.js
    - name: Run Kaizen Unit Test Runner Action
      uses: ./

  test-no-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Kaizen Unit Test Runner Action
      uses: ./

  test-custom-command:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Kaizen Unit Test Runner Action with custom command
      uses: ./
      with:
        test_command: 'echo "Custom test command executed"'